### ISSUE TITLE
0% width triggers exception

### ISSUE THREAD

**Issue by annakolozsvari** [jazzsequence/progress-bar#19]
Hi,
I believe you introduced a major bug in 2.2.0. If width is 0% (which is a valid usecase, sometimes the progress bar is still empty), your wppb_get_progress_bar function interprets that as empty and throws an exception.
The exception triggers a PHP Fatal error. Meaning every site that uses this plugin, and has a page with an empty progressbar, completely breaks.
Please have a look, if you have the time.
Regards,
Anna

**Comment by jazzsequence** [comment]
Thanks for that report. That would have gone out with the 2.2.1 update released yesterday. I should be able to have an update ready today.

**Comment by annakolozsvari** [comment]
Right, sorry!

**Comment by jazzsequence** [comment]
2.2.2 is now available on wp.org. Please check against that and let me know if this issue isn't resolved. Thanks for the bug report! 

https://wordpress.org/plugins/progress-bar/
