### ISSUE TITLE
How to change the visual height of the progress-bar?

### ISSUE THREAD

**Issue by HLXEasy** [jazzsequence/progress-bar#2]
I did not find any option on the CSS documentation, with which the height of the bar could be modified. Is there some CSS tweak available to do so? Or any other idea on how to increase the height?

**Comment by jazzsequence** [comment]
Take a look at the `wppb.css` file in the css folder. There are two height values there that I believe you would need to override in your custom CSS.

**Comment by HLXEasy** [comment]
Thx, got it. Works like a charm.

**Comment by jazzsequence** [comment]
Brilliant! Glad you got it working. 😁
