### ISSUE TITLE
Critical error <PHP 8.0

### ISSUE THREAD

**Issue by annakolozsvari** [jazzsequence/progress-bar#23]
PHP 7.4 and older have reached their end of life, but many sites still run them. If they do, they'll get:
PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /wp-content/plugins/progress-bar/functions.php on line 217

**Comment by jazzsequence** [comment]
You're right and I should probably add a PHP compatibility checker to ensure backwards compatibility. 👍

**Comment by annakolozsvari** [comment]
Thank you for the prompt fix!
