### ISSUE TITLE
https://www.radiomariasp.org/ 

### ISSUE THREAD

**Issue by WFRM-ITStaff** [jazzsequence/progress-bar#3]
Good morning,
The WPMUDEV Defender Pro Security Plugin has identified the following risk

#WordPress Progress Bar plugin <= 2.1.6 - Cross Site Scripting (XSS) vulnerability
-Vulnerability type: Cross Site Scripting (XSS)
-No Update Available

Please inform us if there is a security update to fix it.

**Comment by jazzsequence** [comment]
@WFRM-ITStaff Thanks for the report. Getting ready to push up a 2.2.0 release which should resolve.

**Comment by jazzsequence** [comment]
Resolved in [2.2.0](https://wordpress.org/plugins/progress-bar/)
